# Generated by Django 5.0 on 2025-09-16 18:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_review_likes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='review',
            name='reports',
            field=models.ManyToManyField(blank=True, related_name='reported_reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
